user nginx;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name
            devicehub.putmyhexon.ru

        # Обязательно для Let's Encrypt
        location ^~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
            default_type "text/plain";
            allow all;
        }

        # Любой другой запрос — просто OK
        location / {
            return 200 "certbot bootstrap\n";
        }
    }

    server {
        listen 80;
        server_name
            ldap.putmyhexon.ru

        # Обязательно для Let's Encrypt
        location ^~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
            default_type "text/plain";
            allow all;
        }

        # Любой другой запрос — просто OK
        location / {
            return 200 "certbot bootstrap\n";
        }
    }

    server {
        listen 80;
        server_name
            appium-grid.putmyhexon.ru;

        # Обязательно для Let's Encrypt
        location ^~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
            default_type "text/plain";
            allow all;
        }

        # Любой другой запрос — просто OK
        location / {
            return 200 "certbot bootstrap\n";
        }
    }
}