apiVersion: v1
kind: Service
metadata:
  name: devicehub-ios-bridge-triproxy-dev
  labels:
    app.kubernetes.io/name: devicehub-ios-bridge-triproxy-dev
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: devicehub-triproxy-dev
  ports:
    - name: sub
      port: 7250
      targetPort: 7250
      nodePort: 31250
      protocol: TCP
    - name: push
      port: 7270
      targetPort: 7270
      nodePort: 31270
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: devicehub-ios-bridge-storage-apk
  labels:
    app.kubernetes.io/name: devicehub-ios-bridge-storage-apk
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: devicehub-storage-plugin-apk
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 31300
      protocol: TCP
