apiVersion: v1
kind: Service
metadata:
  name: adbd
  labels:
    app.kubernetes.io/name: adbd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: adbd
  ports:
    - name: adb
      port: 5037
      targetPort: 5037
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: devicehub-provider
  labels:
    app.kubernetes.io/name: devicehub-provider
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: devicehub-provider
  ports:
    - name: p12010
      port: 12010
      targetPort: 12010
      protocol: TCP
    - name: p12011
      port: 12011
      targetPort: 12011
      protocol: TCP
    - name: p12012
      port: 12012
      targetPort: 12012
      protocol: TCP
    - name: p12013
      port: 12013
      targetPort: 12013
      protocol: TCP
    - name: p12014
      port: 12014
      targetPort: 12014
      protocol: TCP
    - name: p12015
      port: 12015
      targetPort: 12015
      protocol: TCP
    - name: p12016
      port: 12016
      targetPort: 12016
      protocol: TCP
    - name: p12017
      port: 12017
      targetPort: 12017
      protocol: TCP
    - name: p12018
      port: 12018
      targetPort: 12018
      protocol: TCP
    - name: p12019
      port: 12019
      targetPort: 12019
      protocol: TCP
    - name: p12020
      port: 12020
      targetPort: 12020
      protocol: TCP
    - name: p12021
      port: 12021
      targetPort: 12021
      protocol: TCP
    - name: p12022
      port: 12022
      targetPort: 12022
      protocol: TCP
    - name: p12023
      port: 12023
      targetPort: 12023
      protocol: TCP
    - name: p12024
      port: 12024
      targetPort: 12024
      protocol: TCP
    - name: p12025
      port: 12025
      targetPort: 12025
      protocol: TCP
    - name: p12026
      port: 12026
      targetPort: 12026
      protocol: TCP
    - name: p12027
      port: 12027
      targetPort: 12027
      protocol: TCP
    - name: p12028
      port: 12028
      targetPort: 12028
      protocol: TCP
    - name: p12029
      port: 12029
      targetPort: 12029
      protocol: TCP
    - name: p12030
      port: 12030
      targetPort: 12030
      protocol: TCP
    - name: p12031
      port: 12031
      targetPort: 12031
      protocol: TCP
    - name: p12032
      port: 12032
      targetPort: 12032
      protocol: TCP
    - name: p12033
      port: 12033
      targetPort: 12033
      protocol: TCP
    - name: p12034
      port: 12034
      targetPort: 12034
      protocol: TCP
    - name: p12035
      port: 12035
      targetPort: 12035
      protocol: TCP
    - name: p12036
      port: 12036
      targetPort: 12036
      protocol: TCP
    - name: p12037
      port: 12037
      targetPort: 12037
      protocol: TCP
    - name: p12038
      port: 12038
      targetPort: 12038
      protocol: TCP
    - name: p12039
      port: 12039
      targetPort: 12039
      protocol: TCP
    - name: p12040
      port: 12040
      targetPort: 12040
      protocol: TCP
