apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devicehub

resources:
  - namespace.yaml
  - devicehub-configmap.yaml
  - devicehub-storage-temp-pvc.yaml
  - devicehub-core-services.yaml
  - devicehub-core-deployments.yaml
  - devicehub-android-services.yaml
  - devicehub-android-deployments.yaml
  - devicehub-dynamic-proxy.yaml
  - devicehub-issuer.yaml
  - devicehub-ingress.yaml
