apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongodb

resources:
  - namespace.yaml
  - mongodb-service.yaml
  - mongodb-pvc.yaml
  - mongodb-statefulset.yaml
  - mongodb-init-job.yaml
  - devicehub-migrate-job.yaml
