apiVersion: v1
kind: Service
metadata:
  name: devicehub-mongo
  labels:
    app.kubernetes.io/name: devicehub-mongo
spec:
  selector:
    app.kubernetes.io/name: devicehub-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
