apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  labels:
    app.kubernetes.io/name: devicehub-mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
