apiVersion: v1
kind: Service
metadata:
  name: devicehub-mongo-external
  labels:
    app.kubernetes.io/name: devicehub-mongo
    app.kubernetes.io/component: external-access
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: devicehub-mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32017
