services:
  certbot:
    image: certbot/certbot:latest
    container_name: devicehub-certbot-issue
    volumes:
      - /home/hex354/certbot/etc/letsencrypt:/etc/letsencrypt
      - /home/hex354/certbot/web:/var/www/certbot
    entrypoint: certbot
